name: Terraform AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Create fresh minimal.tf
      run: |
        rm -f *.tf
        cat > minimal.tf << 'EOF'
        terraform {
          required_providers {
            aws = {
              source = "hashicorp/aws"
            }
          }
        }

        provider "aws" {
          region = "us-east-1"
        }

        # Use existing IAM role
        data "aws_iam_role" "existing_role" {
          name = "WordpressRole"
        }

        # Create only the instance profile with a unique name
        resource "aws_iam_instance_profile" "wordpress_profile" {
          name = "wordpress-profile-new"
          role = data.aws_iam_role.existing_role.name
        }
        EOF
        cat minimal.tf

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve